steps:
  - task: Maven@4
    displayName: 'Build with Maven'
    inputs:
      mavenPOMFile: 'pom.xml'
      goals: 'package'
      options: '--batch-mode --settings .azdo/feed-settings.xml -Dmaven.test.skip=true' 
      jdkVersionOption: '1.11'
    env:
      TOKEN: $(TOKEN)
