# Maven
trigger:
- main

pr:
  branches:
    include:
    - '*'

resources:
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      sourceAnalysisPool:
        name: JEG-windows2022-x64-release
        os: windows
    stages:
    - stage: build
      displayName: Build
      jobs:
      - job: build_windows
        displayName: Build on Windows
        pool:
          name: JEG-windows2022-x64-release
          os: windows
        steps:
        - template: /.azdo/checkout.yml@self
        - template: /.azdo/build.yml@self
        - template: /.azdo/test.yml@self
        - template: /.azdo/publish.yml@self
